# Generated by Django 4.1 on 2022-08-13 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=240, verbose_name="name")),
                ("price", models.FloatField()),
                ("quantity", models.IntegerField()),
                ("desc", models.TextField()),
                ("image", models.CharField(default="img_default", max_length=50)),
            ],
        ),
    ]
